# -*- coding: utf-8 -*-
"""bornhuetter_ferguson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdtJrDoANfrnNqnaQeafQCAkXsdMIiY4
"""

import numpy as np
import pandas as pd


def prepare_bf_inputs(
    ultimate_df: pd.DataFrame,
    original_df: pd.DataFrame,
    premium_col: str = "EarnedPremDIR_C",
) -> pd.DataFrame:
    """
    Prepare BF inputs by attaching premium information
    to the reserving results.

    Required columns:
    - AccidentYear
    - LatestValue
    - CDF
    """

    required_cols = {"AccidentYear", "LatestValue", "CDF"}

    if not required_cols.issubset(ultimate_df.columns):
        missing = required_cols - set(ultimate_df.columns)
        raise ValueError(f"Missing columns: {missing}")

    if premium_col not in original_df.columns:
        raise ValueError(f"Missing premium column '{premium_col}'")

    premium_df = (
        original_df[["AccidentYear", premium_col]]
        .drop_duplicates("AccidentYear")
    )

    data = ultimate_df.merge(
        premium_df,
        on="AccidentYear",
        how="left"
    )

    return data

def apply_bf_guardrails(
    bf_df: pd.DataFrame,
    premium_col: str = "EarnedPremDIR_C",
):
    """
    Remove invalid accident years before BF calculations.
    """

    filtered_df = bf_df[
        (bf_df["LatestValue"] >= 0)
        & (bf_df[premium_col] > 0)
        & (bf_df["CDF"] >= 1)
    ].copy()

    if filtered_df.empty:
        raise ValueError(
            "All accident years removed by guardrails."
        )

    return filtered_df

def calculate_percent_reported(
    bf_df: pd.DataFrame,
):
    """
    Percent Reported = 1 / CDF
    """

    df = bf_df.copy()

    df["Pct_Reported"] = 1 / df["CDF"]

    return df

def calculate_percent_unreported(
    bf_df: pd.DataFrame,
):
    """
    Percent Unreported = 1 - Percent Reported
    """

    df = bf_df.copy()

    df["Pct_Unreported"] = 1 - df["Pct_Reported"]

    return df

def calculate_expected_ultimate(
    bf_df: pd.DataFrame,
    apriori_loss_ratio: float,
    premium_col: str = "EarnedPremDIR_C",
):
    """
    Expected Ultimate = Premium × A Priori Loss Ratio
    """

    df = bf_df.copy()

    df["Expected_Ultimate"] = (
        df[premium_col] * apriori_loss_ratio
    )

    return df

def calculate_bf_ibnr(
    bf_df: pd.DataFrame,
):
    """
    BF IBNR = Expected Ultimate × Percent Unreported
    """

    df = bf_df.copy()

    df["BF_IBNR"] = (
        df["Expected_Ultimate"]
        * df["Pct_Unreported"]
    )

    return df

def calculate_bf_ultimate(
    bf_df: pd.DataFrame,
):
    """
    BF Ultimate = Latest Reported + BF IBNR
    """

    df = bf_df.copy()

    df["BF_Ultimate"] = (
        df["LatestValue"]
        + df["BF_IBNR"]
    )

    return df

def detect_bf_outliers(
    bf_df: pd.DataFrame,
):
    """
    Detect extreme Expected Loss Ratios using IQR.
    """

    lr = (
        bf_df["Expected_Ultimate"]
        / bf_df["EarnedPremDIR_C"]
    )

    q1 = lr.quantile(0.25)
    q3 = lr.quantile(0.75)

    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = bf_df[
        (lr < lower)
        | (lr > upper)
    ]

    return outliers

def bf_stability_analysis(
    bf_df: pd.DataFrame,
):
    """
    Measure reserve volatility.
    """

    return float(
        bf_df["BF_IBNR"].std()
    )

def run_bornhuetter_ferguson(
    ultimate_df: pd.DataFrame,
    original_df: pd.DataFrame,
    apriori_loss_ratio: float = 0.65,
    premium_col: str = "EarnedPremDIR_C",
):
    """
    End-to-end Bornhuetter-Ferguson workflow.

    Steps
    -----
    1. Prepare inputs.
    2. Apply guardrails.
    3. Calculate reported percentages.
    4. Calculate unreported percentages.
    5. Calculate expected ultimate.
    6. Calculate BF IBNR.
    7. Calculate BF Ultimate.
    8. Perform diagnostics.
    """

    print("\n===================================")
    print("BORNHUETTER-FERGUSON METHOD")
    print("===================================")

    bf_df = prepare_bf_inputs(
        ultimate_df,
        original_df,
        premium_col,
    )

    bf_df = apply_bf_guardrails(
        bf_df,
        premium_col,
    )

    bf_df = calculate_percent_reported(
        bf_df
    )

    bf_df = calculate_percent_unreported(
        bf_df
    )

    bf_df = calculate_expected_ultimate(
        bf_df,
        apriori_loss_ratio,
        premium_col,
    )

    bf_df = calculate_bf_ibnr(
        bf_df
    )

    bf_df = calculate_bf_ultimate(
        bf_df
    )

    outliers = detect_bf_outliers(
        bf_df
    )

    volatility = bf_stability_analysis(
        bf_df
    )

    total_ibnr = float(
        bf_df["BF_IBNR"].sum()
    )

    print(f"\nA Priori Loss Ratio : {apriori_loss_ratio:.4f}")
    print(f"Total BF IBNR       : {total_ibnr:,.2f}")
    print(f"Reserve Volatility  : {volatility:,.2f}")

    return {
        "bf_df": bf_df,
        "outliers": outliers,
        "volatility": volatility,
        "total_ibnr": total_ibnr,
    }

