# -*- coding: utf-8 -*-
"""expected_loss_ratio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdtJrDoANfrnNqnaQeafQCAkXsdMIiY4
"""

import numpy as np
import pandas as pd

def prepare_elr_inputs(
    ultimate_df: pd.DataFrame,
    original_df: pd.DataFrame,
    n_mature_years: int = 6,
    premium_col: str = "EarnedPremDIR_C",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Prepare ELR inputs by attaching premium information and splitting
    accident years into mature and immature segments.

    Mature years are used to estimate the expected loss ratio.
    Immature years are projected using the selected ELR.
    """

    required_cols = {"AccidentYear", "Ultimate", "LatestValue"}

    if not required_cols.issubset(ultimate_df.columns):
        missing = required_cols - set(ultimate_df.columns)
        raise ValueError(f"Missing columns in ultimate_df: {missing}")

    if premium_col not in original_df.columns:
        raise ValueError(f"Missing premium column '{premium_col}'")

    premium_df = (
        original_df[["AccidentYear", premium_col]]
        .drop_duplicates("AccidentYear")
    )

    data = ultimate_df.merge(
        premium_df,
        on="AccidentYear",
        how="left"
    )

    mature_df = data.iloc[:n_mature_years].copy()
    immature_df = data.iloc[n_mature_years:].copy()

    if mature_df.empty:
        raise ValueError("No mature accident years found.")

    if immature_df.empty:
        raise ValueError("No immature accident years found.")

    return mature_df, immature_df

def apply_elr_guardrails(
    mature_df: pd.DataFrame,
    premium_col: str = "EarnedPremDIR_C",
    lr_cap: float = 5.0,
) -> pd.DataFrame:
    """
    Remove invalid mature accident years before estimating ELR.
    """

    df = mature_df.copy()

    df["Historical_LR"] = (
        df["Ultimate"] / df[premium_col]
    )

    filtered_df = df[
        (df["Ultimate"] > 0)
        & (df[premium_col] > 0)
        & (df["Historical_LR"] > 0)
        & (df["Historical_LR"] < lr_cap)
    ].copy()

    if filtered_df.empty:
        raise ValueError(
            "All mature years removed by guardrails."
        )

    return filtered_df

def calculate_weighted_elr(
    mature_df: pd.DataFrame,
    premium_col: str = "EarnedPremDIR_C",
) -> float:
    """
    Calculate premium-weighted ELR.

    Formula:

        ELR = Total Ultimate / Total Premium
    """

    total_ultimate = mature_df["Ultimate"].sum()
    total_premium = mature_df[premium_col].sum()

    if total_premium == 0:
        raise ZeroDivisionError(
            "Total premium is zero."
        )

    return float(total_ultimate / total_premium)

def project_elr_ultimates(
    immature_df: pd.DataFrame,
    elr: float,
    premium_col: str = "EarnedPremDIR_C",
) -> pd.DataFrame:
    """
    Project ultimate losses and IBNR for immature years.

    Expected Ultimate = ELR × Premium

    IBNR = Expected Ultimate - Latest Value
    """

    df = immature_df.copy()

    df["Expected_Ultimate"] = (
        elr * df[premium_col]
    )

    df["IBNR"] = (
        df["Expected_Ultimate"] - df["LatestValue"]
    )

    return df

def detect_outlier_accident_years(
    mature_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Detect outlying historical loss ratios using the IQR rule.
    """

    q1 = mature_df["Historical_LR"].quantile(0.25)
    q3 = mature_df["Historical_LR"].quantile(0.75)

    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = mature_df[
        (mature_df["Historical_LR"] < lower)
        | (mature_df["Historical_LR"] > upper)
    ]

    return outliers

def portfolio_stability_analysis(
    mature_df: pd.DataFrame
) -> float:
    """
    Measure volatility of historical loss ratios.
    """

    return float(
        mature_df["Historical_LR"].std()
    )

def run_elr_method(
    ultimate_df: pd.DataFrame,
    original_df: pd.DataFrame,
    n_mature_years: int = 6,
    premium_col: str = "EarnedPremDIR_C",
    lr_cap: float = 5.0,
):
    """
    End-to-end Expected Loss Ratio method.

    Workflow
    --------
    1. Prepare inputs.
    2. Apply guardrails.
    3. Estimate weighted ELR.
    4. Project immature accident years.
    5. Perform diagnostics.
    """

    print("\n==============================")
    print("EXPECTED LOSS RATIO METHOD")
    print("==============================")

    mature_df, immature_df = prepare_elr_inputs(
        ultimate_df,
        original_df,
        n_mature_years,
        premium_col
    )

    mature_df = apply_elr_guardrails(
        mature_df,
        premium_col,
        lr_cap
    )

    elr = calculate_weighted_elr(
        mature_df,
        premium_col
    )

    projected_df = project_elr_ultimates(
        immature_df,
        elr,
        premium_col
    )

    outliers = detect_outlier_accident_years(
        mature_df
    )

    volatility = portfolio_stability_analysis(
        mature_df
    )

    total_ibnr = float(
        projected_df["IBNR"].sum()
    )

    print(f"\nWeighted ELR : {elr:.4f}")
    print(f"Total IBNR   : {total_ibnr:,.2f}")
    print(f"LR Volatility: {volatility:.4f}")

    return {
        "elr": elr,
        "mature_df": mature_df,
        "projected_df": projected_df,
        "outliers": outliers,
        "volatility": volatility,
        "total_ibnr": total_ibnr,
    }

